config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "profiles/:id", to: "pages#user_profile", as: :user_profile

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :cards, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :bookings, only: [:new, :create, :index, :show]
    resources :reviews, only:[:index, :create, :new]
  end

  post 'bookings', to: 'bookings#createmany'
end

app/views/shared/_booking.html.erb
<div class="card-category">
  <div class="card-trip" style="min-height: 100px;" >
    <div class="m-3">
      <% if current_user.id != @card.user_id  %>
        <h3> Book this card </h3>
          <div id='card-booking-dates' data-unavailable="<%= @card.unavailable_dates.to_json %>">
            <%= simple_form_for [@card, @booking] do |f| %>
            <%= f.error_notification %>
              <div class="form-inputs mt-3">
                <%= f.input :start_date,
                            as: :string,
                            type: :DateTimeType,
                            label: false,
                            placeholder: 'Click here to select dates'
                            %>
              </div>
                <div class="info_booking">
                  <div id="price_days">
                  </div>
                </div>
              </div>
                <% end %>
        <% else %>
         <div id="card_owner">
            <h3> This card is owned by you </h3>
            <%=link_to "Go back to your profile", user_profile_path(current_user) %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-category">
  <% if !(params["dates"].nil? || params["dates"]["range"] == "") %>
    <div class="card-trip-selectable" id="<%= card.id %>">
  <% else %>
    <div class="card-trip" id="<%= card.id %>">
  <% end  %>
    <% if !(params[:action] == "show") %>
      <%= link_to card_path(card) do %>
        <%= content_tag :img, "", src: card.img_url %>
      <% end %>
    <% else %>
      <img src=<%= card.img_url %>>
    <% end  %>
    <div class="card-trip-infos">
      <div>
        <h2><%= card.name %></h2>
        <p><%= card.card_type.truncate(26) %></p>
        <br>
        <p>
          <% if card.cmc.nil? %>
            <br>
          <% else %>
            Mana: <%= card.cmc.to_i.round %>
          <% end %>
        </p>
        <p>
          <% if card.power.nil? %>
            <br>
          <% else %>
            Power: <%= card.power.to_i.round %>
          <% end %>
        </p>
        <p>
          <% if card.toughness.nil? %>
            <br>
          <% else %>
            Toughness: <%= card.toughness.to_i.round %>
          <% end %>
        </p>
      </div>
      <h2 class="card-trip-pricing">€<span id="card_price"><%= card.price_per_week %></span></h2>
      <% if !card.color.nil? %>
        <span class="dot" style="background-color: <%= card.color.downcase %>"></span>
      <% else %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_confirmation.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirm your booking</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<div class="my-4">
	        <p class="mb-0"><strong>Your deck</strong></p>
	        <div class="dropdown-divider"></div>
	        <div id="name-list"></div>
        </div>
        <div class="my-4">
	        <p class="mb-0"><strong>Booking period</strong></p>
	        <div class="dropdown-divider"></div>
	        <p>
				<% if params["dates"].nil? %>
				<% else %>
				  <%= params["dates"]["range"] %>
				<% end %>
	        </p>

        </div>
		<div class="my-4">
	        <p class="mb-0"><strong>Total price</strong></p>
	        <div class="dropdown-divider"></div>
	        <p id="total-price">€ 345.00</p>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-flat-grey" data-dismiss="modal">Close</button>
        <%= simple_form_for(booking) do |f| %>
          <% if params["dates"].nil? %>
            <% value_range = "" %>
          <% else %>
            <% value_range = params["dates"]["range"] %>
          <% end %>
          <% value_cards = [1, 2, 3, 4, 5, 6, 7, 8] %>
          <%= hidden_field_tag(:range, value_range) %>
          <%= hidden_field_tag(:cards, value_cards) %>
          <%= f.button :submit, "Book", class: "btn btn-flat", id: "button-book" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/shared/_filter.html.erb
<div id='card-booking-dates'>
  <%= simple_form_for(:dates, method: :get, url: cards_path, wrapper: :inline_form, html: { class: 'form-inline' }) do |f| %>
  	<%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :range,
                  as: :string,
                  type: :DateTimeType,
                  input_html: { value: @last_input, style: "width: 265px; margin-right: 20px;"},
                  required: true,
                  placeholder: "Select booking dates"
                  %>
    </div>
    <div class="form-actions">
      <%= f.button :submit,
      						 "Filter",
      						 style: "margin: 0;",
      						 class: "btn btn-flat"
      						 %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class = "bg-white border-bottom">
  <div class = "container">
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon pl-0">
      <div>
        <%= link_to cards_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", class: "image", style: "width: 150px"; %>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <li class="nav-item">
            </li>

            </li>
            <li class="nav-item dropdown">

            <button class = "navbar-toggle" id = "navbarDropdown" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded= "false">
              <i class="fas fa-bars fa-1x"> </i>
            </button>

              <div class="dropdown-menu dropdown-menu-right border-none border-top" style = "border: none;" aria-labelledby="navbarDropdown">

                <%= link_to "Profile", user_profile_path(current_user), class: "dropdown-item" %>

                <%#= link_to "Favorites", "#", class: "dropdown-item" %>

                <% if policy(Card).create? %>
                  <%= link_to 'Add Card', new_card_path, class: "dropdown-item" %>
                <% end %>

                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            </li>
             <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_reviews.html.erb
  <div class="row row-review">
    <div class="col">
      <div class = "d-flex border-bottom-1" id="new-review">
        <h3> Recent Reviews and Comments </h3>
        <h5>Overall Rating: <%= @overall_rating %></h5>
      </div>
      <% @reviews.last(4).each do |review| %> <!--Only first 4 reviews-->
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-2">
                <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                <p class="text-secondary text-center"><%= time_ago_in_words(review.created_at) %> ago</p>
              </div>
              <div class="col-md-10">
                <p>
                  <strong><%= review.name %></strong></a>
                  <% (review.stars).times do %>
                    <span class="float-right"><i class="text-warning fa fa-star"></i></span>
                  <% end %>
                </p>
                <p> &quot;<%= review.comment %>&quot;</p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class = "col review-col">
      <div class="d-flex justify-content-end">
        <button id = "review-button-new" type="button" class="btn btn-flat"><%= link_to "Write Review", new_card_review_path(@card), style: "color: white;" %></button>
      </div>
    </div>
  </div>

app/views/shared/_selectorbar.html.erb
<% if (params["dates"].nil? || params["dates"]["range"] == "") %>
	<a id="add-to-card"></a>
<% else %>
	<div class="selectorbar cssanimation sequence fadeInBottom">
		<div class="container h-100 d-flex justify-content-between align-items-center">
			<div>
			  <h5 id="typewriter" data-typewriter="Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:),Select cards ...,... you monster hunter,:)"></h5><span class="blinking-cursor">|</span>
			</div>
			<div class="d-flex align-items-center">
				<h5 id="text-count" class="mb-0 pr-3">0 cards selected</h5>
				<h5 id="total-price-preview" class="mb-0 pr-3">(€ 0 total)</h5>
				<a id="add-to-card" href="" class="btn-flat-light" data-toggle="modal" data-target="#exampleModal">Add to cart</a>
			</div>
		</div>
	</div>
<% end %>