config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "profiles/:id", to: "pages#user_profile", as: :user_profile

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :cards, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :bookings, only: [:new, :create, :index, :show]
    resources :reviews, only:[:index, :create, :new]
  end

  post 'bookings', to: 'bookings#createmany'
end

app/views/pages/home.html.erb
<%=  image_tag 'bg.png', id: "video-home" %>

<div class="logo-container">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", style: "width: 100px"; %>
    <% end %>
</div>

<div class="video-container">
  <h1>Welcome to a world of <strong> fantasy </strong> and <strong> imagination </strong>!</h1>
  <p>Real Strategy. Real Challenge</p>
   <%= link_to "Sign up", new_user_registration_path, class: "nav-link", class: "btn btn-flat" %>
   <%= link_to "Log in", new_user_session_path, class: "nav-link", class: "btn btn-flat" %>
  <div class="icon-scroll">
    <div class="mouse">
      <div class="wheel"></div>
    </div>
    <div class="icon-arrows">
      <span></span>
    </div>
  </div>
</div>


<div class="container">
	<h3 class="my-5">Selection of 4 cards</h3>

	<div class="cards pb-5">
	  <% @cards.each do |card| %>
	    <%= render 'shared/card', card: card %>
	  <% end %>
	</div>

	<div class="pb-5 d-flex justify-content-center">
    	<%= link_to "See all", cards_path, :class => "btn btn-flat"%>
	</div>
</div>


<div class="footer">
  <div class="container d-flex justify-content-between">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      © AvantGarde Team
    </div>
  </div>
</div>

app/views/pages/user_profile.html.erb
<div class = "container mx-auto " style="padding-top: 30px ">
<!-- Tab links -->
<div class="tab mx-auto">
  <button class="tablinks active">Profile</button>
  <button class="tablinks">Bookings Received </button>
  <button class="tablinks">Bookings Made </button>
  <button class="tablinks">Cards</button>
</div>

<!-- Tab content -->
<div id="Profile" class="tabcontent" style="display: block;">
  <div class="container" style="padding-top: 15px">
    <div class="row">
          <h4 ><%= @user.first_name + " " + @user.last_name %></h4></div>
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
              <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg"
              id="profile-image1" class="img-circle img-responsive" style = "width:50%; height: 50%">
            </div>
               <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
                <hr>
                  <ul class="container details" >
                    <li><p>
                        <span class="glyphicon glyphicon-envelope one" style="width:25px;"> </span>
                        User Email: <%= @user.email %>
                      </p></li>
                     <li><p>
                        <span class="glyphicon glyphicon-envelope one" style="width:25px;"></span>
                        Account Began: <%= @user.created_at.to_formatted_s(:long)%>
                      </p></li>
                  </ul>
                <hr>
              </div>
       <button class="btn btn-flat" type="submit" style = "color:white">
        <%= link_to "Edit this Profile",  edit_user_registration_path,{:style=>'color:white;'} %></button>
        <%= link_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-flat" %></p>
      </div>
  </div>




<div id="Bookings Received" class="tabcontent">
    <div class="container" style="padding-top: 15px">
      <div class="row">
        <div class="col-lg-6">
          <h4>Upcoming bookings </h4>
            <% @bookings_received_upcoming.each do |b| %>
          <div class="card-product" style="margin-top: 10px">
            <%= image_tag b.card.img_url %>
              <div class="card-product-infos">
                  <h4> <%= b.card.name %>  </h4>
                  <p> Start date: <%= b.start_date %> </p>
                  <p> End date: <%= b.end_date %></p>
                  <p> Total price: $ <%= b.total_price %> </p>
            </div>
          </div>
          <% end %>
        </div>


        <div class="col-lg-6">
          <h4>Past bookings</h4>
            <% @bookings_received_past.each do |b| %>
          <div class="card-product" style="margin-top: 10px">
             <%= image_tag b.card.img_url %>
              <div class="card-product-infos">
                <h4> <%= b.card.name %>  </h4>
                <p> Start date: <%= b.start_date %> </p>
                <p> End date: <%= b.end_date %></p>
              <p> Total price: $ <%= b.total_price %> </p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>




<div id="Bookings Made" class="tabcontent">
    <div class="container" style="padding-top: 15px">
      <div class="row">
        <div class="col-lg-6">
          <h4>My upcoming bookings</h4>
            <% @bookings_made_upcoming.each do |b| %>
              <div class="card-product" style="margin-top: 10px">
                <%= image_tag b.card.img_url %>
                  <div class="card-product-infos">
                    <h4> <%= b.card.name %>  </h4>
                    <p> Start date: <%= b.start_date %> </p>
                    <p> End date: <%= b.end_date %></p>
                    <p> Total price: $ <%= b.total_price %> </p>
                  </div>
                </div>
              <% end %>
            </div>

        <div class="col-lg-6">
          <h4>My past bookings</h4>
            <% @bookings_made_past.each do |b| %>
          <div class="card-product" style="margin-top: 10px">
            <%= image_tag b.card.img_url %>
              <div class="card-product-infos">
                <h4> <%= b.card.name %>  </h4>
                <p> Start date: <%= b.start_date %> </p>
                <p> End date: <%= b.end_date %></p>
              <p> Total price: $ <%= b.total_price %> </p>
            </div>
          </div>
        <% end %>
      </div>
      </div>

    </div>
  </div>


<div id="Cards" class="tabcontent">
  <div class="container" style="padding-top: 15px">

    <div style=" display: flex; justify-content: space-between; padding: 10px;" >
      <h4>Cards</h4>
        <% if policy(Card).create? %>
        <%= link_to 'Add Card', new_card_path %>
      <% end %>
    </div>

      <div class="cards pb-5">
        <% @cards.each_with_index do |card, index| %>
          <div class="card-category">
            <% if !(params["dates"].nil? || params["dates"]["range"] == "") %>
              <div class="card-trip-selectable" id="<%= card.id %>">
            <% else %>
              <div class="card-trip" id="<%= card.id %>">
            <% end  %>
                 <div class="overlay">
                  <%= link_to "Edit", edit_card_path(card), class: "btn btn-flat edit-button"%>
                  <% if card.bookings.empty? %>
                    <button data-id="<%= card.id %>" id="sweet-alert-demo-<%= card.id %>" class="sweet-alert-btn btn btn-flat">Delete</button>
                    <%= link_to '', card_path(card), method: :delete, id: "delete-link-#{card.id}", class: "hidden" %>
                  <% else %>
                    <button class="button-not-delete btn btn-flat">Delete</button>
                  <% end %>
                </div>
              <% if !(params[:action] == "show") %>
                <%= link_to card_path(card) do %>
                  <%= content_tag :img, "", src: card.img_url %>
                <% end %>
              <% else %>
                <img src=<%= card.img_url %>>
              <% end  %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= card.name %></h2>
                  <p><%= card.card_type.truncate(26) %></p>
                  <br>
                  <p>
                    <% if card.cmc.nil? %>
                      <br>
                    <% else %>
                      Mana: <%= card.cmc.to_i.round %>
                    <% end %>
                  </p>
                  <p>
                    <% if card.power.nil? %>
                      <br>
                    <% else %>
                      Power: <%= card.power.to_i.round %>
                    <% end %>
                  </p>
                  <p>
                    <% if card.toughness.nil? %>
                      <br>
                    <% else %>
                      Toughness: <%= card.toughness.to_i.round %>
                    <% end %>
                  </p>
                </div>
                <h2 class="card-trip-pricing">€<span id="card_price"><%= card.price_per_week %></span></h2>
                <% if !card.color.nil? %>
                  <span class="dot" style="background-color: <%= card.color.downcase %>"></span>
                <% else %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>